/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-FAB-SPOILERS-7yf3At5dqFSmvPZlCkM-YpUNZG7H8D2W",
  "version": "2020-11-20"
}

export default ebconfig;